## POPULATION WEBScrape

In [1]:
# Import relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup 
import matplotlib.pyplot as plt
import pandas as pd
import dask.dataframe as dd

In [2]:
browser = Browser('chrome')

The chromedriver version (124.0.6367.91) detected in PATH at C:\Program Files\webdriver\chromedriver.exe might not be compatible with the detected chrome version (125.0.6422.176); currently, chromedriver 125.0.6422.141 is recommended for chrome 125.*, so it is advised to delete the driver in PATH and retry

In [3]:
# Visit the website
# reference https://static.bc-edx.com/data/web/mars_facts/temperature.html
url = "https://www.worldometers.info/coronavirus/#countries"
browser.visit(url)

In [4]:
# Create a Beautiful Soup Object
html = browser.html
soup = BeautifulSoup(html, 'html.parser')

In [19]:
# Extract all rows of data
table = soup.find('table', class_='table')
rows = table.find_all('tr')

In [20]:
# Create an empty list to store each row of data
country_data = []


# Loop through the scraped rows to create a list of rows
for x in rows[1:]:
        td = x.find_all('td')
        row = [col.text for col in td]
        country_data.append(row)
country_data

[['',
  'World',
  '704,753,890',
  '0',
  '7,010,681',
  '0',
  '675,619,811',
  '+790',
  '22,123,398',
  '34,794',
  '90,413',
  '899.4',
  '',
  '',
  '',
  'All'],
 ['',
  '\nEurope\n',
  '253,406,198',
  '',
  '2,101,824',
  '',
  '248,754,104',
  '+474',
  '2,550,270',
  '4,453',
  '',
  '',
  '',
  '',
  '',
  'Europe'],
 ['',
  '\nAsia\n',
  '221,500,265',
  '',
  '1,553,662',
  '',
  '205,673,091',
  '',
  '14,273,512',
  '14,733',
  '',
  '',
  '',
  '',
  '',
  'Asia'],
 ['',
  '\nNorth America\n',
  '131,889,132',
  '',
  '1,695,941',
  '',
  '127,665,129',
  '+350',
  '2,528,062',
  '6,095',
  '',
  '',
  '',
  '',
  '',
  'North America'],
 ['1',
  'USA',
  '111,820,082',
  '',
  '1,219,487                                ',
  '',
  '109,814,428',
  '',
  '786,167',
  '940',
  '333,985',
  '3,642',
  '1,186,851,502',
  '3,544,901',
  '334,805,269 ',
  'North America'],
 ['',
  '\nSouth America\n',
  '70,200,879',
  '',
  '1,367,332',
  '',
  '66,683,585',
  '',
  '2,149,962',
  '8,953',
  '',
  '',
  '',
  '',
  '',
  'South America'],
 ['2',
  'India',
  '45,035,393',
  '',
  '533,570                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '32,016',
  '379',
  '935,879,495',
  '665,334',
  '1,406,631,776 ',
  'Asia'],
 ['3',
  'France',
  '40,138,560',
  '',
  '167,642                                ',
  '',
  '39,970,918',
  '',
  '0',
  '',
  '612,013',
  '2,556',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe'],
 ['4',
  'Germany',
  '38,828,995',
  '',
  '183,027                                ',
  '',
  '38,240,600',
  '',
  '405,368',
  'N/A',
  '462,891',
  '2,182',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe'],
 ['5',
  'Brazil',
  '38,743,918',
  '',
  '711,380                                ',
  '',
  '36,249,161',
  '',
  '1,783,377',
  'N/A',
  '179,908',
  '3,303',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America'],
 ['6',
  'S. Korea',
  '34,571,873',
  '',
  '35,934                                ',
  '',
  '34,535,939',
  '',
  '0',
  '',
  '673,523',
  '700',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia'],
 ['7',
  'Japan',
  '33,803,572',
  '',
  '74,694                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '269,169',
  '595',
  '100,414,883',
  '799,578',
  '125,584,838 ',
  'Asia'],
 ['8',
  'Italy',
  '26,723,249',
  '',
  '196,487                                ',
  '',
  '26,361,218',
  '',
  '165,544',
  '22',
  '443,445',
  '3,261',
  '281,126,449',
  '4,665,010',
  '60,262,770 ',
  'Europe'],
 ['9',
  'UK',
  '24,910,387',
  '',
  '232,112                                ',
  '',
  '24,678,275',
  '',
  '0',
  'N/A',
  '363,666',
  '3,389',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe'],
 ['10',
  'Russia',
  '24,124,215',
  '',
  '402,756                                ',
  '',
  '23,545,818',
  '',
  '175,641',
  'N/A',
  '165,454',
  '2,762',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe'],
 ['11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia'],
 ['',
  '\nOceania\n',
  '14,895,771',
  '',
  '33,015',
  '',
  '14,752,388',
  '',
  '110,368',
  '31',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania'],
 ['12',
  'Spain',
  '13,914,811',
  '',
  '121,760                                ',
  '',
  '13,762,417',
  '',
  '30,634',
  '231',
  '297,840',
  '2,606',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe'],
 ['',
  '\nAfrica\n',
  '12,860,924',
  '',
  '258,892',
  '',
  '12,090,808',
  '',
  '511,224',
  '529',
  '',
  '',
  '',
  '',
  '',
  'Africa'],
 ['13',
  'Australia',
  '11,853,144',
  '',
  '24,414                                ',
  '',
  '11,820,014',
  '',
  '8,716',
  '3',
  '454,687',
  '937',
  '81,916,639',
  '3,142,326',
  '26,068,792 ',
  'Australia/Oceania'],
 ['14',
  'Vietnam',
  '11,625,195',
  '',
  '43,206                                ',
  '',
  '10,640,971',
  '',
  '941,018',
  '',
  '117,481',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia'],
 ['15',
  'Taiwan',
  '10,241,523',
  '',
  '19,005                                ',
  '',
  '10,222,518',
  '',
  '0',
  '',
  '428,720',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia'],
 ['16',
  'Argentina',
  '10,128,845',
  '',
  '130,841                                ',
  '',
  '9,997,258',
  '',
  '746',
  '',
  '220,143',
  '2,844',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America'],
 ['17',
  'Netherlands',
  '8,635,786',
  '',
  '22,992                                ',
  '',
  '8,612,599',
  '',
  '195',
  'N/A',
  '501,747',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe'],
 ['18',
  'Mexico',
  '7,702,809',
  '',
  '334,958                                ',
  '',
  '6,899,865',
  '',
  '467,986',
  'N/A',
  '58,549',
  '2,546',
  '20,013,810',
  '152,124',
  '131,562,772 ',
  'North America'],
 ['19',
  'Iran',
  '7,627,186',
  '',
  '146,811                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '88,665',
  '1,707',
  '57,320,267',
  '666,338',
  '86,022,837 ',
  'Asia'],
 ['20',
  'Indonesia',
  '6,829,221',
  '',
  '162,063                                ',
  '',
  '6,647,104',
  '',
  '20,054',
  'N/A',
  '24,466',
  '581',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia'],
 ['21',
  'Poland',
  '6,661,991',
  '',
  '120,598                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '176,524',
  '3,196',
  '39,323,709',
  '1,041,970',
  '37,739,785 ',
  'Europe'],
 ['22',
  'Colombia',
  '6,400,173',
  '',
  '143,200                                ',
  '',
  '6,212,152',
  '',
  '44,821',
  '342',
  '124,244',
  '2,780',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America'],
 ['23',
  'Greece',
  '6,101,379',
  '',
  '37,869                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '591,412',
  '3,671',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe'],
 ['24',
  'Austria',
  '6,081,287',
  '',
  '22,542                                ',
  '',
  '6,054,934',
  '',
  '3,811',
  '',
  '670,727',
  '2,486',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe'],
 ['25',
  'Portugal',
  '5,643,062',
  '',
  '28,126                                ',
  '',
  '5,614,809',
  '',
  '127',
  '61',
  '556,484',
  '2,774',
  '46,139,518',
  '4,549,993',
  '10,140,570 ',
  'Europe'],
 ['26',
  'Ukraine',
  '5,557,995',
  '',
  '112,418                                ',
  '',
  '5,445,577',
  '',
  '0',
  '',
  '128,681',
  '2,603',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe'],
 ['27',
  'Chile',
  '5,384,853',
  '',
  '64,497                                ',
  '',
  '5,252,450',
  '',
  '67,906',
  '7',
  '279,730',
  '3,350',
  '50,382,097',
  '2,617,225',
  '19,250,195 ',
  'South America'],
 ['28',
  'Malaysia',
  '5,278,406',
  '',
  '37,348                                ',
  '',
  '5,233,268',
  '',
  '7,790',
  '11',
  '159,079',
  '1,126',
  '68,580,916',
  '2,066,869',
  '33,181,072 ',
  'Asia'],
 ['29',
  'Canada',
  '4,946,090',
  '',
  '59,034                                ',
  '',
  '4,881,312',
  '+350',
  '5,744',
  '99',
  '128,843',
  '1,538',
  '66,572,774',
  '1,734,189',
  '38,388,419 ',
  'North America'],
 ['30',
  'Belgium',
  '4,861,695',
  '',
  '34,376                                ',
  '',
  '4,826,798',
  '+50',
  '521',
  'N/A',
  '416,659',
  '2,946',
  '37,454,182',
  '3,209,915',
  '11,668,278 ',
  'Europe'],
 ['31',
  'Israel',
  '4,841,772',
  '',
  '12,707                                ',
  '',
  '4,798,473',
  '',
  '30,592',
  'N/A',
  '519,169',
  '1,363',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia'],
 ['32',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia'],
 ['33',
  'Thailand',
  '4,770,149',
  '',
  '34,586                                ',
  '',
  '4,692,636',
  '',
  '42,927',
  'N/A',
  '68,069',
  '494',
  '17,273,454',
  '246,488',
  '70,078,203 ',
  'Asia'],
 ['34',
  'Czechia',
  '4,759,041',
  '',
  '43,517                                ',
  '',
  '4,715,206',
  '',
  '318',
  '2',
  '443,246',
  '4,053',
  '57,834,241',
  '5,386,552',
  '10,736,784 ',
  'Europe'],
 ['35',
  'Peru',
  '4,572,667',
  '',
  '222,161                                ',
  '',
  '4,350,506',
  '',
  '0',
  '4',
  '135,751',
  '6,595',
  '39,010,194',
  '1,158,115',
  '33,684,208 ',
  'South America'],
 ['36',
  'Switzerland',
  '4,453,053',
  '',
  '14,452                                ',
  '',
  '4,438,309',
  '',
  '292',
  'N/A',
  '507,549',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe'],
 ['37',
  'Philippines',
  '4,140,383',
  '',
  '66,864                                ',
  '',
  '4,067,381',
  '',
  '6,138',
  'N/A',
  '36,800',
  '594',
  '36,102,746',
  '320,888',
  '112,508,994 ',
  'Asia'],
 ['38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa'],
 ['39',
  'Romania',
  '3,529,735',
  '',
  '68,929                                ',
  '',
  '3,460,149',
  '+390',
  '657',
  '21',
  '185,470',
  '3,622',
  '28,758,667',
  '1,511,122',
  '19,031,335 ',
  'Europe'],
 ['40',
  'Denmark',
  '3,183,756',
  '',
  '8,814                                ',
  '',
  '3,174,942',
  '',
  '0',
  '',
  '545,636',
  '1,511',
  '129,333,107',
  '22,165,247',
  '5,834,950 ',
  'Europe'],
 ['41',
  'Singapore',
  '3,006,155',
  '',
  '2,024                                ',
  '',
  '3,004,131',
  '',
  '0',
  '4',
  '505,785',
  '341',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia'],
 ['42',
  'Hong Kong',
  '2,937,609',
  '',
  '14,924                                ',
  '',
  '2,916,005',
  '',
  '6,680',
  'N/A',
  '386,309',
  '1,963',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia'],
 ['43',
  'Sweden',
  '2,754,129',
  '',
  '27,407                                ',
  '',
  '2,726,492',
  '+20',
  '230',
  'N/A',
  '269,511',
  '2,682',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe'],
 ['44',
  'New Zealand',
  '2,621,111',
  '',
  '5,697                                ',
  '',
  '2,613,791',
  '',
  '1,623',
  '',
  '535,117',
  '1,163',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania'],
 ['45',
  'Serbia',
  '2,615,054',
  '',
  '18,057                                ',
  '',
  '2,596,608',
  '',
  '389',
  '',
  '302,213',
  '2,087',
  '13,463,733',
  '1,555,958',
  '8,653,016 ',
  'Europe'],
 ['46',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia'],
 ['47',
  'Hungary',
  '2,230,232',
  '',
  '49,048                                ',
  '',
  '2,152,155',
  '',
  '29,029',
  '',
  '232,164',
  '5,106',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe'],
 ['48',
  'Bangladesh',
  '2,049,377',
  '',
  '29,493                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '12,207',
  '176',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia'],
 ['49',
  'Slovakia',
  '1,877,605',
  '',
  '21,224                                ',
  '',
  '1,856,381',
  '',
  '0',
  '23',
  '343,872',
  '3,887',
  '7,448,789',
  '1,364,199',
  '5,460,193 ',
  'Europe'],
 ['50',
  'Georgia',
  '1,861,665',
  '',
  '17,132                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '469,082',
  '4,317',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia'],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia'],
 ['52',
  'Ireland',
  '1,734,582',
  '',
  '9,491                                ',
  '',
  '1,724,921',
  '',
  '170',
  '19',
  '345,521',
  '1,891',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe'],
 ['53',
  'Pakistan',
  '1,581,936',
  '',
  '30,664                                ',
  '',
  '1,538,689',
  '',
  '12,583',
  '',
  '6,893',
  '134',
  '30,589,153',
  '133,292',
  '229,488,994 ',
  'Asia'],
 ['54',
  'Finland',
  '1,516,117',
  '',
  '11,958                                ',
  '',
  '1,503,989',
  '+14',
  '170',
  'N/A',
  '272,930',
  '2,153',
  '12,108,977',
  '2,179,850',
  '5,554,960 ',
  'Europe'],
 ['55',
  'Norway',
  '1,509,732',
  '',
  '6,638                                ',
  '',
  '1,503,094',
  '',
  '0',
  'N/A',
  '273,930',
  '1,204',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe'],
 ['56',
  'Kazakhstan',
  '1,411,831',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,963',
  '24',
  '73,514',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia'],
 ['57',
  'Lithuania',
  '1,397,806',
  '',
  '9,897                                ',
  '',
  '1,387,478',
  '',
  '431',
  'N/A',
  '525,154',
  '3,718',
  '10,540,357',
  '3,959,997',
  '2,661,708 ',
  'Europe'],
 ['58',
  'Slovenia',
  '1,356,546',
  '',
  '7,100                                ',
  '',
  '1,349,424',
  '',
  '22',
  'N/A',
  '652,803',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe'],
 ['59',
  'Bulgaria',
  '1,339,851',
  '',
  '38,748                                ',
  '',
  '1,292,944',
  '',
  '8,159',
  '22',
  '195,753',
  '5,661',
  '11,671,043',
  '1,705,147',
  '6,844,597 ',
  'Europe'],
 ['60',
  'Croatia',
  '1,309,728',
  '',
  '18,687                                ',
  '',
  '1,258,432',
  '',
  '32,609',
  '',
  '322,650',
  '4,604',
  '5,660,084',
  '1,394,355',
  '4,059,286 ',
  'Europe'],
 ['61',
  'Guatemala',
  '1,291,293',
  '',
  '20,289                                ',
  '',
  '1,269,891',
  '',
  '1,113',
  '5',
  '69,484',
  '1,092',
  '7,593,848',
  '408,622',
  '18,584,039 ',
  'North America'],
 ['62',
  'Morocco',
  '1,278,992',
  '',
  '16,303                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '33,860',
  '432',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa'],
 ['63',
  'Lebanon',
  '1,243,838',
  '',
  '10,952                                ',
  '',
  '1,087,587',
  '',
  '145,299',
  '74',
  '186,068',
  '1,638',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia'],
 ['64',
  'Costa Rica',
  '1,238,883',
  '',
  '9,428                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '239,058',
  '1,819',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America'],
 ['65',
  'Bolivia',
  '1,212,131',
  '',
  '22,407                                ',
  '',
  '1,177,145',
  '',
  '12,579',
  '220',
  '101,073',
  '1,868',
  '2,710,261',
  '225,993',
  '11,992,656 ',
  'South America'],
 ['66',
  'Tunisia',
  '1,153,361',
  '',
  '29,423                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '95,741',
  '2,442',
  '5,013,383',
  '416,164',
  '12,046,656 ',
  'Africa'],
 ['67',
  'Cuba',
  '1,115,251',
  '',
  '8,530                                ',
  '',
  '1,106,660',
  '',
  '61',
  '',
  '98,645',
  '754',
  '14,402,674',
  '1,273,936',
  '11,305,652 ',
  'North America'],
 ['68',
  'Ecuador',
  '1,070,188',
  '',
  '36,043                                ',
  '',
  '1,034,145',
  '',
  '0',
  '',
  '59,083',
  '1,990',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America'],
 ['69',
  'UAE',
  '1,067,030',
  '',
  '2,349                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '105,837',
  '233',
  '200,732,262',
  '19,910,389',
  '10,081,785 ',
  'Asia'],
 ['70',
  'Panama',
  '1,059,893',
  '',
  '8,727                                ',
  '',
  '1,051,102',
  '',
  '64',
  '16',
  '238,341',
  '1,962',
  '7,882,622',
  '1,772,585',
  '4,446,964 ',
  'North America'],
 ['71',
  'Uruguay',
  '1,041,111',
  '',
  '7,664                                ',
  '',
  '1,030,944',
  '',
  '2,503',
  '18',
  '297,799',
  '2,192',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America'],
 ['72',
  'Mongolia',
  '1,011,496',
  '',
  '2,284                                ',
  '',
  '1,009,212',
  '',
  '0',
  'N/A',
  '299,429',
  '676',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia'],
 ['73',
  'Nepal',
  '1,003,450',
  '',
  '12,031                                ',
  '',
  '991,322',
  '',
  '97',
  '',
  '33,199',
  '398',
  '6,047,766',
  '200,088',
  '30,225,582 ',
  'Asia'],
 ['74',
  'Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  '',
  '105,381',
  '755',
  '13,646,641',
  '1,446,722',
  '9,432,800 ',
  'Europe'],
 ['75',
  'Latvia',
  '982,505',
  '',
  '6,715                                ',
  '',
  '971,406',
  '',
  '4,384',
  '',
  '531,418',
  '3,632',
  '7,885,792',
  '4,265,272',
  '1,848,837 ',
  'Europe'],
 ['76',
  'Saudi Arabia',
  '841,469',
  '',
  '9,646                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '23,475',
  '269',
  '45,481,735',
  '1,268,848',
  '35,844,909 ',
  'Asia'],
 ['77',
  'Paraguay',
  '837,602',
  '',
  '20,155                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '114,648',
  '2,759',
  '2,657,506',
  '363,751',
  '7,305,843 ',
  'South America'],
 ['78',
  'Azerbaijan',
  '835,234',
  '',
  '10,400                                ',
  '',
  '824,089',
  '',
  '745',
  '',
  '81,089',
  '1,010',
  '7,748,050',
  '752,223',
  '10,300,205 ',
  'Asia'],
 ['79',
  'Bahrain',
  '729,549',
  '',
  '1,574                                ',
  '',
  '727,915',
  '',
  '60',
  'N/A',
  '408,944',
  '882',
  '10,948,549',
  '6,137,138',
  '1,783,983 ',
  'Asia'],
 ['80',
  'Cyprus',
  '681,110',
  '',
  '1,365                                ',
  '',
  '679,745',
  '',
  '0',
  '',
  '556,741',
  '1,116',
  '9,640,118',
  '7,879,860',
  '1,223,387 ',
  'Asia'],
 ['81',
  'Dominican Republic',
  '675,890',
  '',
  '4,384                                ',
  '',
  '671,316',
  '',
  '190',
  '4',
  '61,131',
  '397',
  '3,740,928',
  '338,350',
  '11,056,370 ',
  'North America'],
 ['82',
  'Sri Lanka',
  '672,754',
  '',
  '16,897                                ',
  '',
  '655,852',
  '',
  '5',
  '',
  '31,181',
  '783',
  '6,486,117',
  '300,619',
  '21,575,842 ',
  'Asia'],
 ['83',
  'Kuwait',
  '667,158',
  '',
  '2,570                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '152,308',
  '587',
  '8,455,743',
  '1,930,391',
  '4,380,326 ',
  'Asia'],
 ['84',
  'Myanmar',
  '641,873',
  '',
  '19,495                                ',
  '',
  '620,159',
  '',
  '2,219',
  '',
  '11,622',
  '353',
  '11,711,514',
  '212,061',
  '55,227,143 ',
  'Asia'],
 ['85',
  'Moldova',
  '635,145',
  '',
  '12,218                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '158,265',
  '3,044',
  '3,216,305',
  '801,437',
  '4,013,171 ',
  'Europe'],
 ['86',
  'Estonia',
  '628,070',
  '',
  '3,001                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  'N/A',
  '475,123',
  '2,270',
  '6,968,103',
  '5,271,239',
  '1,321,910 ',
  'Europe'],
 ['87',
  'Palestine',
  '621,008',
  '',
  '5,404                                ',
  '',
  '615,445',
  '',
  '159',
  '',
  '116,173',
  '1,011',
  '3,078,533',
  '575,907',
  '5,345,541 ',
  'Asia'],
 ['88',
  'Venezuela',
  '552,695',
  '',
  '5,856                                ',
  '',
  '546,537',
  '',
  '302',
  '31',
  '18,885',
  '200',
  '3,359,014',
  '114,771',
  '29,266,991 ',
  'South America'],
 ['89',
  'Egypt',
  '516,023',
  '',

In [22]:
country_data  = pd.DataFrame(country_data , columns = ['id','Country', 'Total_Cases', 'New_Cases', 'Total_Deaths', 'Total_Recovered', 'New_Recovered', 'Active', 'Serious', 'trash10', 'trash11', 'trash12','trash13','trash14','trash15','trash16','trash17','trash18','trash19','trash20','trash21','trash22'])

In [23]:
print(country_data .dtypes)

id                 object
Country            object
Total_Cases        object
New_Cases          object
Total_Deaths       object
Total_Recovered    object
New_Recovered      object
Active             object
Serious            object
trash10            object
trash11            object
trash12            object
trash13            object
trash14            object
trash15            object
trash16            object
trash17            object
trash18            object
trash19            object
trash20            object
trash21            object
trash22            object
dtype: object

In [24]:
print(country_data)

    id            Country  Total_Cases New_Cases  \
0                   World  704,753,890         0
1              \nEurope\n  253,406,198
2                \nAsia\n  221,500,265
3       \nNorth America\n  131,889,132
4    1                USA  111,820,082
..  ..                ...          ...       ...
242                Total:   70,200,879
243                Total:   14,895,771
244                Total:   12,860,924
245                Total:          721
246                Total:  704,753,890         0

                                  Total_Deaths Total_Recovered New_Recovered  \
0                                    7,010,681               0   675,619,811
1                                    2,101,824                   248,754,104
2                                    1,553,662                   205,673,091
3                                    1,695,941                   127,665,129
4    1,219,487                                                   109,814,428
..                                         ...             ...           ...
242                                  1,367,332                    66,683,585
243                                     33,015                    14,752,388
244                                    258,892                    12,090,808
245                                         15                           706
246                                  7,010,681               0   675,619,811

    Active     Serious trash10  ...        trash13    trash14       trash15  \
0     +790  22,123,398  34,794  ...
1     +474   2,550,270   4,453  ...
2           14,273,512  14,733  ...
3     +350   2,528,062   6,095  ...
4              786,167     940  ...  1,186,851,502  3,544,901  334,805,269
..     ...         ...     ...  ...            ...        ...           ...
242          2,149,962   8,953  ...
243            110,368      31  ...
244            511,224     529  ...
245                  0       0  ...
246   +790  22,123,398  34,794  ...

               trash16 trash17 trash18 trash19 trash20 trash21 trash22
0                  All    None    None    None    None    None    None
1               Europe    None    None    None    None    None    None
2                 Asia    None    None    None    None    None    None
3        North America    None    None    None    None    None    None
4        North America    None    None    None    None    None    None
..                 ...     ...     ...     ...     ...     ...     ...
242      South America
243  Australia/Oceania
244             Africa
245
246                All      \n

[247 rows x 22 columns]

In [19]:
# Write the data to a CSV
country_data.to_csv('country_data_webscrape.csv', index=False)
print("Completed csv transfer")

Completed csv transfer

In [20]:
browser.quit()